create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  role text not null default 'viewer' check (role in ('viewer', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title_fr text not null,
  title_en text not null,
  category text not null,
  description_fr text not null,
  description_en text not null,
  tags text[] not null default '{}',
  impact text,
  metrics_type text,
  color text default 'primary',
  image_url text,
  gallery_urls text[] not null default '{}',
  project_url text,
  is_locked boolean not null default false,
  is_featured boolean not null default false,
  status_fr text,
  status_en text,
  sort_order int not null default 0,
  status text not null default 'published' check (status in ('draft', 'published', 'archived')),
  published_at timestamptz,
  version int not null default 1,
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sections (
  id text primary key,
  title_fr text not null,
  title_en text not null,
  content_fr text,
  content_en text,
  is_enabled boolean not null default true,
  sort_order int not null default 0,
  status text not null default 'published' check (status in ('draft', 'published', 'archived')),
  published_at timestamptz,
  version int not null default 1,
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.links (
  id uuid primary key default gen_random_uuid(),
  slug text unique,
  label text not null,
  href text not null,
  section_id text references public.sections(id) on delete set null,
  is_external boolean not null default true,
  is_enabled boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.theme_settings (
  key text primary key,
  value jsonb not null,
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  key text primary key,
  value jsonb not null,
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.media_assets (
  id uuid primary key default gen_random_uuid(),
  bucket text not null default 'portfolio-media',
  path text not null,
  alt_text text,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.visitor_sessions (
  id uuid primary key default gen_random_uuid(),
  session_token text unique not null,
  country text,
  city text,
  lat double precision,
  lng double precision,
  device text,
  browser text,
  os text,
  referrer text,
  language text,
  started_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create table if not exists public.page_views (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.visitor_sessions(id) on delete cascade,
  page_path text not null,
  page_title text,
  event_type text not null default 'page_view',
  occurred_at timestamptz not null default now()
);

create table if not exists public.click_events (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.visitor_sessions(id) on delete cascade,
  page_path text not null,
  element_text text,
  element_href text,
  link_id text,
  section_id text,
  event_type text not null default 'click',
  occurred_at timestamptz not null default now()
);

create table if not exists public.section_events (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.visitor_sessions(id) on delete cascade,
  page_path text not null,
  section_id text not null,
  event_type text not null default 'section_view',
  occurred_at timestamptz not null default now()
);

create table if not exists public.admin_audit_logs (
  id uuid primary key default gen_random_uuid(),
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity text not null,
  entity_id text,
  diff jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_projects_sort_order on public.projects(sort_order);
create index if not exists idx_page_views_occurred_at on public.page_views(occurred_at desc);
create index if not exists idx_page_views_page_path on public.page_views(page_path);
create index if not exists idx_click_events_occurred_at on public.click_events(occurred_at desc);
create index if not exists idx_click_events_section_id on public.click_events(section_id);
create index if not exists idx_section_events_occurred_at on public.section_events(occurred_at desc);
create index if not exists idx_section_events_section_id on public.section_events(section_id);
create index if not exists idx_visitor_sessions_last_seen on public.visitor_sessions(last_seen_at desc);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_projects_touch on public.projects;
create trigger trg_projects_touch before update on public.projects
for each row execute function public.touch_updated_at();

drop trigger if exists trg_sections_touch on public.sections;
create trigger trg_sections_touch before update on public.sections
for each row execute function public.touch_updated_at();

drop trigger if exists trg_links_touch on public.links;
create trigger trg_links_touch before update on public.links
for each row execute function public.touch_updated_at();

drop trigger if exists trg_theme_settings_touch on public.theme_settings;
create trigger trg_theme_settings_touch before update on public.theme_settings
for each row execute function public.touch_updated_at();

drop trigger if exists trg_site_settings_touch on public.site_settings;
create trigger trg_site_settings_touch before update on public.site_settings
for each row execute function public.touch_updated_at();

alter table public.profiles enable row level security;
alter table public.projects enable row level security;
alter table public.sections enable row level security;
alter table public.links enable row level security;
alter table public.theme_settings enable row level security;
alter table public.site_settings enable row level security;
alter table public.media_assets enable row level security;
alter table public.visitor_sessions enable row level security;
alter table public.page_views enable row level security;
alter table public.click_events enable row level security;
alter table public.section_events enable row level security;
alter table public.admin_audit_logs enable row level security;

create or replace function public.is_admin(uid uuid)
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = uid
      and p.role = 'admin'
  );
$$;

drop policy if exists "Public can read published projects" on public.projects;
create policy "Public can read published projects" on public.projects
for select using (status = 'published');

drop policy if exists "Admins full access projects" on public.projects;
create policy "Admins full access projects" on public.projects
for all using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists "Public can read published sections" on public.sections;
create policy "Public can read published sections" on public.sections
for select using (status = 'published');

drop policy if exists "Admins full access sections" on public.sections;
create policy "Admins full access sections" on public.sections
for all using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists "Public can read enabled links" on public.links;
create policy "Public can read enabled links" on public.links
for select using (is_enabled = true);

drop policy if exists "Admins full access links" on public.links;
create policy "Admins full access links" on public.links
for all using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists "Admins only theme settings" on public.theme_settings;
create policy "Admins only theme settings" on public.theme_settings
for all using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists "Admins only site settings" on public.site_settings;
create policy "Admins only site settings" on public.site_settings
for all using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists "Admins only media assets" on public.media_assets;
create policy "Admins only media assets" on public.media_assets
for all using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists "Anyone can insert visitor sessions" on public.visitor_sessions;
create policy "Anyone can insert visitor sessions" on public.visitor_sessions
for insert with check (true);

drop policy if exists "Anyone can update own visitor session" on public.visitor_sessions;
create policy "Anyone can update own visitor session" on public.visitor_sessions
for update using (true) with check (true);

drop policy if exists "Admins can read visitor sessions" on public.visitor_sessions;
create policy "Admins can read visitor sessions" on public.visitor_sessions
for select using (public.is_admin(auth.uid()));

drop policy if exists "Anyone can insert page views" on public.page_views;
create policy "Anyone can insert page views" on public.page_views
for insert with check (true);

drop policy if exists "Admins can read page views" on public.page_views;
create policy "Admins can read page views" on public.page_views
for select using (public.is_admin(auth.uid()));

drop policy if exists "Anyone can insert click events" on public.click_events;
create policy "Anyone can insert click events" on public.click_events
for insert with check (true);

drop policy if exists "Admins can read click events" on public.click_events;
create policy "Admins can read click events" on public.click_events
for select using (public.is_admin(auth.uid()));

drop policy if exists "Anyone can insert section events" on public.section_events;
create policy "Anyone can insert section events" on public.section_events
for insert with check (true);

drop policy if exists "Admins can read section events" on public.section_events;
create policy "Admins can read section events" on public.section_events
for select using (public.is_admin(auth.uid()));

drop policy if exists "Admins manage profiles" on public.profiles;
create policy "Admins manage profiles" on public.profiles
for all using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile" on public.profiles
for select using (auth.uid() = id);

drop policy if exists "Admins only audit logs" on public.admin_audit_logs;
create policy "Admins only audit logs" on public.admin_audit_logs
for all using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

create or replace view public.analytics_live_overview as
select
  (select count(*) from public.visitor_sessions where last_seen_at > now() - interval '5 minutes') as active_visitors,
  (select count(*) from public.page_views where occurred_at > now() - interval '24 hours') as page_views_24h,
  (select count(*) from public.click_events where occurred_at > now() - interval '24 hours') as clicks_24h,
  (select count(*) from public.section_events where occurred_at > now() - interval '24 hours') as section_views_24h;

