create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  name text not null,
  role text,
  company text,
  text text not null,
  rating int not null default 5,
  avatar_url text,
  stats text,
  impact text,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  icon_name text not null default 'Code2',
  title_fr text not null,
  title_en text not null,
  description_fr text not null,
  description_en text not null,
  skills text[] not null default '{}',
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.sections add column if not exists icon_name text;
alter table public.sections add column if not exists description_fr text;
alter table public.sections add column if not exists description_en text;

create or replace function public.get_sections_ordered()
returns setof public.sections
language sql stable
as $$
  select * from public.sections order by sort_order asc, id asc;
$$;

alter table public.testimonials enable row level security;
alter table public.services enable row level security;

create policy "Anyone can read testimonials" on public.testimonials
  for select using (true);

create policy "Admin can insert testimonials" on public.testimonials
  for insert with check (true);

create policy "Admin can update testimonials" on public.testimonials
  for update using (true);

create policy "Admin can delete testimonials" on public.testimonials
  for delete using (true);

create policy "Anyone can read services" on public.services
  for select using (true);

create policy "Admin can insert services" on public.services
  for insert with check (true);

create policy "Admin can update services" on public.services
  for update using (true);

create policy "Admin can delete services" on public.services
  for delete using (true);

-- Seed data for sections (portfolio structure)
insert into public.sections (id, title_fr, title_en, description_fr, description_en, icon_name, is_enabled, sort_order) values
  ('hero', 'Hero', 'Hero', 'Section d''accueil avec présentation', 'Home section with introduction', 'Layout', true, 0),
  ('apropos', 'À propos', 'About', 'Qui je suis et ce que je fais', 'Who I am and what I do', 'UserRound', true, 1),
  ('arsenal', 'Arsenal Technique', 'Tech Arsenal', 'Mes compétences techniques', 'My technical skills', 'Cpu', true, 2),
  ('projects', 'Projets', 'Projects', 'Mes réalisations phares', 'My featured projects', 'Globe', true, 3),
  ('services', 'Services', 'Services', 'Ce que je propose', 'What I offer', 'Mail', true, 4),
  ('temoignages', 'Témoignages', 'Testimonials', 'Ce que disent mes clients', 'What my clients say', 'Quote', true, 5),
  ('contact', 'Contact', 'Contact', 'Me contacter', 'Get in touch', 'Mail', true, 6)
on conflict (id) do update set
  title_fr = excluded.title_fr,
  title_en = excluded.title_en,
  description_fr = excluded.description_fr,
  description_en = excluded.description_en,
  is_enabled = excluded.is_enabled,
  sort_order = excluded.sort_order;
